type User {
  _id: ID
  username: String! @unique
  email: String!
  password: String!
  avatar: String
  joinDate: String
  favorites: [Post]
}

type Post {
  _id: ID
  title: String!
  imageUrl: String
  categories: [String]!
  description: String
  createdDate: String
  likes: Int
  userId: User!
  messages: [Message]
}

type Message {
  _id: ID
  messageBody: String!
  messageDate: String
  messageUser: User!
}

type PostsPage {
 posts: [Post]
 hasMore: Boolean
}

type Query {
  getCurrentUser: User
  getPosts: [Post]
  infiniteScrollPosts(pageNum: Int!, pageSize: Int!): PostsPage

}

type Token {
  token: String!
}

type Mutation {
  addPost(
    title: String!
    imageUrl: String!
    categories: [String]!
    description: String!
    userId: ID!
  ): Post!
  registerUser(username: String!, email: String!, password: String!): Token!
  loginUser(email: String!, password: String!): Token!
}
